#!/usr/bin/env bash

##############################################################################################
##############################################################################################
#Descrição do programa : Usuário entra com um link de site / IP e retorna o status com o comando PING.
#Autor : Carlos Huerta
#Versão : 1.0
#Changelog : -
##############################################################################################
##############################################################################################



read -p "Digite o Endereço de um Site : " link

for sites in "$link"; do

exec_=$(ping -c2 "$link")

echo "Retorno de testes do ping foi : $exec_"

done
